### ISSUE TITLE
roslint_add_test() doesn't break the build when there is error

### ISSUE THREAD

**Issue by commaster90** [ros/roslint#29]
When "roslint_add_test()" is used in the CMakeLists.txt, "catkin_make run_tests" is able to execute roslint and populate the errors in the RESULTS_FILE.
However, this does not break the test and catkin_make completes without error.

**Comment by jack-oquin** [comment]
Thanks for the report. That is certainly not the way one would want it behave.

If you have a patch for this problem, please submit a pull request.

**Comment by mikepurvis** [comment]
I see this behaviour as well, and I agree it is undesirable. However, I'm having trouble figuring out where it is coming from. The roslint test is patterned after roslaunch file checks, cf.

https://github.com/ros/ros_comm/blob/indigo-devel/tools/roslaunch/cmake/roslaunch-extras.cmake.em#L40
https://github.com/ros/roslint/blob/master/cmake/roslint-extras.cmake.em#L78

I've verified that the `test_wrapper` script correctly returns 1 rather than 0 on failure. And it certainly seems like that should fail it:

https://github.com/ros/catkin/blob/indigo-devel/cmake/test/tests.cmake#L128-129

So I'm not sure what to say here. @dirk-thomas, any thoughts as to why a non-zero return code from roslint's test wrapper could not fail the test target?

**Comment by dirk-thomas** [comment]
I don't know much about roslint and I certainly don't understand the question.

But tests in general are not supposed to "break the build". A package is first being built and afterwards some tests are being run. Individual tests may fail / have a return code of non-zero and each test should create a JUnit style result file.

If you can provide an easy to reproduce instructions what you are doing and what the actual as well as expected result is I might be able to take a closer look and provide feedback.

**Comment by commaster90** [comment]
I think it's my mistake. I thought that invoking "catkin_make run_tests" should display all the test errors but in fact it doesn't have to. The summary of the test results will only be shown by invoking "catkin_test_results build/test_results".

**Comment by mikepurvis** [comment]
Okay, yes, I've confirmed that a `catkin_make run_tests` with failing gtests still "succeeds" as a build, it just has angry red output in the console letting you know that there was a failure. So the real bug here is probably that the wrapper script should send an angry red message to stderr on failure.

Though the JUnit output definitely works, as I've had that hit me on the buildfarm.

**Comment by jack-oquin** [comment]
I would prefer that ``catkin_make run_tests`` provide a non-zero return status if one or more tests fail. 

But, I guess it does not work that way. Too bad, but probably not fixable at this point.

**Comment by dirk-thomas** [comment]
Automated scripts have no way to distinguish an error from a failed test in that case.

That's why `catkin_make` does not return an error code when a test fails. But you can invoke `catkin_test_resutls` afterwards to determine if tests have failed using its return code.

**Comment by jack-oquin** [comment]
Many people would probably expect that a build which explicitly invoked the tests *has* failed if any test failed.

But, I understand that it is not going to change at this point. Perhaps the catkin documentation should be updated to explain this feature and suggest using ``catkin_test_results`` as a work-around.

**Comment by mikepurvis** [comment]
Because the `run_tests` target is not part of ALL, I feel like you could make a case for `catkin_make` to succeed, and `catkin_make tests` to succeed, but `catkin_make run_tests` to fail.

But there is then still the issue of not wanting the build to abort in the face of the first failed test.

Anyway, thanks for the explanation, @dirk-thomas.
