### ISSUE TITLE
Need support for #ifndef guards with package name

### ISSUE THREAD

**Issue by DLu** [ros/roslint#30]
The [recommended style](http://wiki.ros.org/CppStyleGuide#A.23ifndef_guards) for #ifndef guards includes the package name

 ``#ifndef PACKAGE_PATH_FILE_H``

This tool suggests only [PATH_FILE_H](https://github.com/ros/roslint/blob/master/src/roslint/cpplint.py#L1432)

**Unless I'm invoking the roslint tool with the wrong parameters. The documentation isn't super clear on the CLI.

**Comment by mikepurvis** [comment]
Since headers are always placed in a directory named after the package, I felt it was safe to use the cpplint.py logic as-is. Unless a7bcfd2cf975ab2cb1920b290bf3fcd05c476fc1 introduced a bug, the `navigation/costmap_2d/include/costmap_2d/costmap_2d.h` header should use the following guard:

    #ifndef COSTMAP_2D_COSTMAP_2D_H

CLI isn't really a supported use-case for roslint, though I suppose it could be with some effort toward verification and docs. Can you verify that you get the same behaviour when you use the CMake functions?

**Comment by DLu** [comment]
Is there a way to run through the CMake functions while filtering out certain categories?

**Comment by DLu** [comment]
Ok, using the CMake functions, the correct guards are suggested/tested for. I believe the same functionality could be replicated using the CLI if I used the proper "root" perhaps. Any hints there?

**Comment by mikepurvis** [comment]
You can define `ROSLINT_CPP_OPTS` to disable filters— for example, by default we turn off the references warning, as that trips up on the standard service call signature:

https://github.com/ros/roslint/blob/master/cmake/roslint-extras.cmake.em#L55

The working directory should just be the root of the package (eg, the directory which contains src and include).

**Comment by DLu** [comment]
Ok, I figured it out. I matters where you run the file from. 

```
$ rosrun roslint cpplint costmap_2d.h
costmap_2d.h:38:  #ifndef header guard has wrong style, please use: COSTMAP_2D_H  [build/header_guard] [5]
$ cd ..
$ rosrun roslint cpplint costmap_2d/costmap_2d.h 
costmap_2d/costmap_2d.h:38:  #ifndef header guard has wrong style, please use: COSTMAP_2D_COSTMAP_2D_H  [build/header_guard] [5]
```
