### ISSUE TITLE
C++11 bracer-init-list fails to pass

### ISSUE THREAD

**Issue by asiron** [ros/roslint#62]
The following code:
```
server = registerServer("server_name", {State::First, State::Second});
```
where we pass C++11 bracer-init-list as the second argument fails to pass the `CheckBracers`. The special case where both bracers happen to be on the same line fails because only one character is expected after the closing bracer `}`, but in our case we have 2 characters `});`
https://github.com/ros/roslint/blob/63e81f9197926504a5071ff546c9cbb345398b50/src/roslint/cpplint_wrapper.py#L85-L93

Chaninging the line
https://github.com/ros/roslint/blob/63e81f9197926504a5071ff546c9cbb345398b50/src/roslint/cpplint_wrapper.py#L89
to
```python
if Match(r'^(.*){(.*)}.+$', line): 
```
would probably solve the issue, but as I am not an expert in writing linters, it could potentially break other stuff.
Any suggestions ?

**Comment by mikepurvis** [comment]
I'm far from an expert in this area either, but I do know this rule/regex has caused a lot of grief, particularly with various new C++11 features.

If you make the final matcher be `.*` rather than `.+`, then the change will be strictly increasing tolerance, and thus safe in terms of not invalidating something which previously passed. Please send a PR for such a change.
